server:
  addr: 8888

autocode:
  root: ""

zap:
  director: log
  format: console
  stacktrace-key: stacktrace
  encode-level: LowercaseColorLevelEncoder
  prefix: [MEIS_server]
  level: info
  log-in-console: true
  show-line: true

system:
  db-type: mysql


mysql:
  path: "127.0.0.1"
  port: "3306"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "meis"
  username: "root"
  password: "123456"
  log-zap: false
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
